os: linux
dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
  - '7.3'

before_install: 
  - pecl install pecl_http <<< ''
  - composer self-update

install:
  - composer install

script: 
  - phpunit
